language: objective-c
matrix:
  include:
    - env: OSX=10.12
      os: osx
      osx_image: xcode9
      rvm: system

before_install:
  - brew tap krmnn/homebrew-audio 

script:
  - travis_wait 40 brew install --verbose Formula/ardour5.rb
  - brew test Formula/ardour5.rb

notifications:
  email:
    on_success: never
    on_failure: always
